// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arkcfkxalnadnnrvmjsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFya2Nma3hhbG5hZG5ucnZtanNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjIxNTUsImV4cCI6MjA3NDYzODE1NX0._tZ2LS3XG88LFMVczzc9mJzbcIMgv6k6Ye0fUi8UOGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});